"""Add KDMLabAttempt table

Revision ID: 134b9e2a4940
Revises: 
Create Date: 2025-10-08 16:43:33.341855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '134b9e2a4940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_roll_assignment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('admin_roll_assignment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('co_marks', schema=None) as batch_op:
        batch_op.alter_column('marks_obtained',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('max_marks',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('last_updated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index('unique_user_co')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('kdm_lab_criteria', schema=None) as batch_op:
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('kdm_lab_criteria_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'kdm_lab_experiment', ['experiment_id'], ['id'])

    with op.batch_alter_table('kdm_lab_experiment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('kdm_lab_manual_marks', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('criteria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('kdm_lab_manual_marks_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])

    with op.batch_alter_table('kdm_lab_response', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('criteria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('selected_option',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.drop_constraint('kdm_lab_response_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('kdm_lab_response_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'kdm_lab_experiment', ['experiment_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'kdm_lab_criteria', ['criteria_id'], ['id'])

    with op.batch_alter_table('problem_visibility', schema=None) as batch_op:
        batch_op.drop_index('unique_problem_admin')
        batch_op.create_unique_constraint('_problem_admin_uc', ['problem_number', 'admin_id'])
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('completed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_quiz_attempts_user_quiz')

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('choices',
               existing_type=mysql.JSON(),
               nullable=False)
        batch_op.alter_column('correct_answers',
               existing_type=mysql.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.drop_index('idx_quiz_questions_co')

    with op.batch_alter_table('quiz_responses', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('points_earned',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('answered_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index('idx_quiz_responses_attempt')

    with op.batch_alter_table('quiz_visibility', schema=None) as batch_op:
        batch_op.alter_column('released_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('rollnumber',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('phonenumber',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('completed',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'student'"))
        batch_op.alter_column('reg_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reg_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'student'"))
        batch_op.alter_column('completed',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('rollnumber',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('quiz_visibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('released_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('quiz_responses', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_responses_attempt', ['attempt_id'], unique=False)
        batch_op.alter_column('answered_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('points_earned',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_questions_co', ['co_number'], unique=False)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('correct_answers',
               existing_type=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('choices',
               existing_type=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_attempts_user_quiz', ['user_id', 'quiz_name'], unique=False)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('problem_visibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_problem_admin_uc', type_='unique')
        batch_op.create_index('unique_problem_admin', ['problem_number', 'admin_id'], unique=True)

    with op.batch_alter_table('kdm_lab_response', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kdm_lab_response_ibfk_2', 'kdm_lab_criteria', ['criteria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('kdm_lab_response_ibfk_1', 'kdm_lab_experiment', ['experiment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('selected_option',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('criteria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('kdm_lab_manual_marks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kdm_lab_manual_marks_ibfk_1', 'kdm_lab_criteria', ['criteria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('criteria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('kdm_lab_experiment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('kdm_lab_criteria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kdm_lab_criteria_ibfk_1', 'kdm_lab_experiment', ['experiment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('experiment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('co_marks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('unique_user_co', ['user_id', 'co_number'], unique=True)
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('percentage',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('max_marks',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.alter_column('marks_obtained',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('admin_roll_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_roll_assignment_ibfk_1', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
